version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - URL=http://scopify.work/
      - PORT=80
    networks:
      - re
  redis:
    image: redis
    networks:
      - re

networks:
  re:
    external:
      name: infra_redis
